package com.eve.smarttrader.rest.models.jpa;

// Generated 28 avr. 2013 21:59:35 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HistoryId generated by hbm2java
 */
@Embeddable
public class HistoryId implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Date date;
    private long marketHistoryId;

    public HistoryId() {
    }

    public HistoryId(Date date, long marketHistoryId) {
        this.date = date;
        this.marketHistoryId = marketHistoryId;
    }

    @Column(name = "date", nullable = false, length = 19)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Column(name = "marketHistory_id", nullable = false)
    public long getMarketHistoryId() {
        return this.marketHistoryId;
    }

    public void setMarketHistoryId(long marketHistoryId) {
        this.marketHistoryId = marketHistoryId;
    }

    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null) {
            return false;
        }
        if (!(other instanceof HistoryId)) {
            return false;
        }
        HistoryId castOther = (HistoryId) other;

        return ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null && this.getDate().equals(castOther.getDate()))) && (this.getMarketHistoryId() == castOther.getMarketHistoryId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
        result = 37 * result + (int) this.getMarketHistoryId();
        return result;
    }

}
