package com.eve.smarttrader.rest.models.jpa;

// Generated 28 avr. 2013 21:59:35 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * History generated by hbm2java
 */
@Entity
@Table(name = "history", catalog = "eve")
public class History implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private HistoryId id;
    private MarketHistory marketHistory;
    private long average;
    private long high;
    private long low;
    private long orders;
    private long quantity;

    public History() {
    }

    public History(HistoryId id, MarketHistory marketHistory, long average, long high, long low, long orders, long quantity) {
        this.id = id;
        this.marketHistory = marketHistory;
        this.average = average;
        this.high = high;
        this.low = low;
        this.orders = orders;
        this.quantity = quantity;
    }

    @EmbeddedId
    @AttributeOverrides({ @AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 19)), @AttributeOverride(name = "marketHistoryId", column = @Column(name = "marketHistory_id", nullable = false)) })
    public HistoryId getId() {
        return this.id;
    }

    public void setId(HistoryId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "marketHistory_id", nullable = false, insertable = false, updatable = false)
    public MarketHistory getMarketHistory() {
        return this.marketHistory;
    }

    public void setMarketHistory(MarketHistory marketHistory) {
        this.marketHistory = marketHistory;
    }

    @Column(name = "average", nullable = false)
    public long getAverage() {
        return this.average;
    }

    public void setAverage(long average) {
        this.average = average;
    }

    @Column(name = "high", nullable = false)
    public long getHigh() {
        return this.high;
    }

    public void setHigh(long high) {
        this.high = high;
    }

    @Column(name = "low", nullable = false)
    public long getLow() {
        return this.low;
    }

    public void setLow(long low) {
        this.low = low;
    }

    @Column(name = "orders", nullable = false)
    public long getOrders() {
        return this.orders;
    }

    public void setOrders(long orders) {
        this.orders = orders;
    }

    @Column(name = "quantity", nullable = false)
    public long getQuantity() {
        return this.quantity;
    }

    public void setQuantity(long quantity) {
        this.quantity = quantity;
    }

}
