package com.eve.smarttrader.rest.models.jpa;

// Generated 28 avr. 2013 21:59:35 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "invtypes", catalog = "eve")
public class Item implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private long typeId;
    private Integer groupId;
    private String typeName;
    private String description;
    private Double mass;
    private Double volume;
    private Double capacity;
    private Integer portionSize;
    private Integer raceId;
    private BigDecimal basePrice;
    private Integer published;
    private Integer marketGroupId;
    private Double chanceOfDuplicating;

    public Item() {
    }

    public Item(long typeId) {
        this.typeId = typeId;
    }

    public Item(long typeId, Integer groupId, String typeName, String description, Double mass, Double volume, Double capacity, Integer portionSize, Integer raceId, BigDecimal basePrice, Integer published, Integer marketGroupId, Double chanceOfDuplicating) {
        this.typeId = typeId;
        this.groupId = groupId;
        this.typeName = typeName;
        this.description = description;
        this.mass = mass;
        this.volume = volume;
        this.capacity = capacity;
        this.portionSize = portionSize;
        this.raceId = raceId;
        this.basePrice = basePrice;
        this.published = published;
        this.marketGroupId = marketGroupId;
        this.chanceOfDuplicating = chanceOfDuplicating;
    }

    @Id
    @Column(name = "typeID", unique = true, nullable = false)
    public long getTypeId() {
        return this.typeId;
    }

    public void setTypeId(long typeId) {
        this.typeId = typeId;
    }

    @Column(name = "groupID")
    public Integer getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    @Column(name = "typeName", length = 100)
    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Column(name = "description", length = 3000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "mass", precision = 22, scale = 0)
    public Double getMass() {
        return this.mass;
    }

    public void setMass(Double mass) {
        this.mass = mass;
    }

    @Column(name = "volume", precision = 22, scale = 0)
    public Double getVolume() {
        return this.volume;
    }

    public void setVolume(Double volume) {
        this.volume = volume;
    }

    @Column(name = "capacity", precision = 22, scale = 0)
    public Double getCapacity() {
        return this.capacity;
    }

    public void setCapacity(Double capacity) {
        this.capacity = capacity;
    }

    @Column(name = "portionSize")
    public Integer getPortionSize() {
        return this.portionSize;
    }

    public void setPortionSize(Integer portionSize) {
        this.portionSize = portionSize;
    }

    @Column(name = "raceID")
    public Integer getRaceId() {
        return this.raceId;
    }

    public void setRaceId(Integer raceId) {
        this.raceId = raceId;
    }

    @Column(name = "basePrice", scale = 4)
    public BigDecimal getBasePrice() {
        return this.basePrice;
    }

    public void setBasePrice(BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    @Column(name = "published")
    public Integer getPublished() {
        return this.published;
    }

    public void setPublished(Integer published) {
        this.published = published;
    }

    @Column(name = "marketGroupID")
    public Integer getMarketGroupId() {
        return this.marketGroupId;
    }

    public void setMarketGroupId(Integer marketGroupId) {
        this.marketGroupId = marketGroupId;
    }

    @Column(name = "chanceOfDuplicating", precision = 22, scale = 0)
    public Double getChanceOfDuplicating() {
        return this.chanceOfDuplicating;
    }

    public void setChanceOfDuplicating(Double chanceOfDuplicating) {
        this.chanceOfDuplicating = chanceOfDuplicating;
    }

}
