package com.eve.smarttrader.rest.models.jpa;

// Generated 28 avr. 2013 21:59:35 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MarketGroup generated by hbm2java
 */
@Entity
@Table(name = "invmarketgroups", catalog = "eve")
public class MarketGroup implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private int marketGroupId;
    private MarketGroup marketGroup;
    private String marketGroupName;
    private String description;
    private Integer iconId;
    private Integer hasTypes;
    private Set<MarketGroup> marketGroups = new HashSet<MarketGroup>(0);

    public MarketGroup() {
    }

    public MarketGroup(int marketGroupId) {
        this.marketGroupId = marketGroupId;
    }

    public MarketGroup(int marketGroupId, MarketGroup marketGroup, String marketGroupName, String description, Integer iconId, Integer hasTypes, Set<MarketGroup> marketGroups) {
        this.marketGroupId = marketGroupId;
        this.marketGroup = marketGroup;
        this.marketGroupName = marketGroupName;
        this.description = description;
        this.iconId = iconId;
        this.hasTypes = hasTypes;
        this.marketGroups = marketGroups;
    }

    @Id
    @Column(name = "marketGroupID", unique = true, nullable = false)
    public int getMarketGroupId() {
        return this.marketGroupId;
    }

    public void setMarketGroupId(int marketGroupId) {
        this.marketGroupId = marketGroupId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parentGroupID")
    public MarketGroup getMarketGroup() {
        return this.marketGroup;
    }

    public void setMarketGroup(MarketGroup marketGroup) {
        this.marketGroup = marketGroup;
    }

    @Column(name = "marketGroupName", length = 100)
    public String getMarketGroupName() {
        return this.marketGroupName;
    }

    public void setMarketGroupName(String marketGroupName) {
        this.marketGroupName = marketGroupName;
    }

    @Column(name = "description", length = 3000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "iconID")
    public Integer getIconId() {
        return this.iconId;
    }

    public void setIconId(Integer iconId) {
        this.iconId = iconId;
    }

    @Column(name = "hasTypes")
    public Integer getHasTypes() {
        return this.hasTypes;
    }

    public void setHasTypes(Integer hasTypes) {
        this.hasTypes = hasTypes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "marketGroup")
    public Set<MarketGroup> getMarketGroups() {
        return this.marketGroups;
    }

    public void setMarketGroups(Set<MarketGroup> marketGroups) {
        this.marketGroups = marketGroups;
    }

}
